/* automatically generated from clock-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (clock_dialog_ui)
#endif
#ifdef __GNUC__
static const char clock_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char clock_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.20\"/><requires lib=\"libxfce4ui-2\" version=\"4.12\"/"
  "><object class=\"GtkAdjustment\" id=\"fuzziness\"><property name=\"uppe"
  "r\">3</property><property name=\"step_increment\">1</property><property"
  " name=\"page_increment\">1</property><property name=\"page_size\">1</pr"
  "operty></object><object class=\"GtkImage\" id=\"image1\"><property name"
  "=\"visible\">True</property><property name=\"can_focus\">False</propert"
  "y><property name=\"icon_name\">time-admin</property></object><object cl"
  "ass=\"GtkImage\" id=\"image2\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><property name=\"icon_na"
  "me\">window-close-symbolic</property></object><object class=\"GtkImage\""
  " id=\"image3\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">False</property><property name=\"icon_name\">help-browse"
  "r</property></object><object class=\"GtkListStore\" id=\"mode-model\"><"
  "columns><column type=\"gchararray\"/></columns><data><row><col id=\"0\""
  " translatable=\"yes\">Analog</col></row><row><col id=\"0\" translatable"
  "=\"yes\">Binary</col></row><row><col id=\"0\" translatable=\"yes\">Digi"
  "tal</col></row><row><col id=\"0\" translatable=\"yes\">Fuzzy</col></row"
  "><row><col id=\"0\" translatable=\"yes\">LCD</col></row></data></object"
  "><object class=\"XfceTitledDialog\" id=\"dialog\"><property name=\"can_"
  "focus\">False</property><property name=\"title\" translatable=\"yes\">C"
  "lock</property><property name=\"icon_name\">org.xfce.panel.clock</prope"
  "rty><property name=\"type_hint\">normal</property><child internal-child"
  "=\"vbox\"><object class=\"GtkBox\" id=\"dialog-vbox2\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"orientation\">vertical</property><property name=\"spaci"
  "ng\">2</property><child internal-child=\"action_area\"><object class=\""
  "GtkButtonBox\" id=\"dialog-action_area2\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"layout_style\">end</property><child><object class=\"GtkButton\" id="
  "\"close-button\"><property name=\"label\" translatable=\"yes\">_Close</"
  "property><property name=\"visible\">True</property><property name=\"can"
  "_focus\">True</property><property name=\"receives_default\">True</prope"
  "rty><property name=\"image\">image2</property><property name=\"use_unde"
  "rline\">True</property></object><packing><property name=\"expand\">Fals"
  "e</property><property name=\"fill\">False</property><property name=\"po"
  "sition\">0</property></packing></child><child><object class=\"GtkButton"
  "\" id=\"help-button\"><property name=\"label\" translatable=\"yes\">_He"
  "lp</property><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"receives_default\">True</pr"
  "operty><property name=\"image\">image3</property><property name=\"use_u"
  "nderline\">True</property></object><packing><property name=\"expand\">F"
  "alse</property><property name=\"fill\">False</property><property name=\""
  "position\">1</property><property name=\"secondary\">True</property></pa"
  "cking></child></object><packing><property name=\"expand\">False</proper"
  "ty><property name=\"fill\">True</property><property name=\"pack_type\">"
  "end</property><property name=\"position\">0</property></packing></child"
  "><child><object class=\"GtkBox\" id=\"vbox1\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"border_width\">6</property><property name=\"orientation\">vertic"
  "al</property><property name=\"spacing\">6</property><child><object clas"
  "s=\"GtkFrame\" id=\"frame2\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">False</property><property name=\"margin_bo"
  "ttom\">18</property><property name=\"label_xalign\">0</property><proper"
  "ty name=\"shadow_type\">none</property><child><object class=\"GtkGrid\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"margin_left\">18</property><property "
  "name=\"row_spacing\">6</property><property name=\"column_spacing\">12</"
  "property><child><object class=\"GtkEntry\" id=\"timezone-name\"><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">True</p"
  "roperty><property name=\"hexpand\">True</property><property name=\"invi"
  "sible_char\">\342\227\217</property><property name=\"secondary_icon_nam"
  "e\">help-contents</property><property name=\"primary_icon_activatable\""
  ">False</property><property name=\"secondary_icon_tooltip_text\" transla"
  "table=\"yes\">Name of a timezone corresponding a file in the zoneinfo d"
  "atabase, for example \"America/New_York\". Leave empty to use the local"
  "time.</property></object><packing><property name=\"left_attach\">1</pro"
  "perty><property name=\"top_attach\">0</property></packing></child><chil"
  "d><object class=\"GtkLabel\" id=\"label9\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><property na"
  "me=\"label\" translatable=\"yes\">Time_zone:</property><property name=\""
  "use_underline\">True</property><property name=\"xalign\">0</property></"
  "object><packing><property name=\"left_attach\">0</property><property na"
  "me=\"top_attach\">0</property></packing></child><child><object class=\""
  "GtkButton\" id=\"run-time-config-tool\"><property name=\"label\" transl"
  "atable=\"yes\">Time and Date _Settings...</property><property name=\"us"
  "e_action_appearance\">False</property><property name=\"visible\">True</"
  "property><property name=\"can_focus\">True</property><property name=\"r"
  "eceives_default\">True</property><property name=\"image\">image1</prope"
  "rty><property name=\"use_underline\">True</property></object><packing><"
  "property name=\"left_attach\">0</property><property name=\"top_attach\""
  ">1</property></packing></child><child><placeholder/></child></object></"
  "child><child type=\"label\"><object class=\"GtkLabel\" id=\"label6\"><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Fa"
  "lse</property><property name=\"margin_bottom\">6</property><property na"
  "me=\"label\" translatable=\"yes\">Time Settings</property><attributes><"
  "attribute name=\"weight\" value=\"bold\"/></attributes></object></child"
  "></object><packing><property name=\"expand\">False</property><property "
  "name=\"fill\">True</property><property name=\"position\">0</property></"
  "packing></child><child><object class=\"GtkFrame\" id=\"frame3\"><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">False</"
  "property><property name=\"margin_bottom\">18</property><property name=\""
  "label_xalign\">0</property><property name=\"shadow_type\">none</propert"
  "y><child><object class=\"GtkGrid\"><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">False</property><property name=\"mar"
  "gin_left\">18</property><property name=\"row_spacing\">6</property><pro"
  "perty name=\"column_spacing\">12</property><child><object class=\"GtkEn"
  "try\" id=\"tooltip-format\"><property name=\"visible\">True</property><"
  "property name=\"can_focus\">True</property><property name=\"hexpand\">T"
  "rue</property><property name=\"secondary_icon_name\">help-contents</pro"
  "perty><property name=\"primary_icon_activatable\">False</property><prop"
  "erty name=\"secondary_icon_tooltip_text\" translatable=\"yes\">The form"
  "at describes the date and time parts to insert into the panel. For exam"
  "ple, %Y will be substituted with the year, %m with the month and %d wit"
  "h the day. Similarly, &lt;b&gt;&lt;/b&gt; tags will make the text bold."
  " See the \"Help\" page for additional information.</property></object><"
  "packing><property name=\"left_attach\">0</property><property name=\"top"
  "_attach\">2</property><property name=\"width\">2</property></packing></"
  "child><child><object class=\"GtkComboBox\" id=\"tooltip-chooser\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property><property name=\"hexpand\">False</property><child><object cl"
  "ass=\"GtkCellRendererText\" id=\"cellrenderertext2\"/><attributes><attr"
  "ibute name=\"text\">2</attribute></attributes></child></object><packing"
  "><property name=\"left_attach\">1</property><property name=\"top_attach"
  "\">1</property></packing></child><child><object class=\"GtkComboBox\" i"
  "d=\"mode\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">False</property><property name=\"hexpand\">True</property><p"
  "roperty name=\"model\">mode-model</property><child><object class=\"GtkC"
  "ellRendererText\" id=\"cellrenderertext1\"/><attributes><attribute name"
  "=\"text\">0</attribute></attributes></child></object><packing><property"
  " name=\"left_attach\">1</property><property name=\"top_attach\">0</prop"
  "erty></packing></child><child><object class=\"GtkLabel\" id=\"label4\">"
  "<property name=\"visible\">True</property><property name=\"can_focus\">"
  "False</property><property name=\"label\" translatable=\"yes\">_Tooltip "
  "format:</property><property name=\"use_underline\">True</property><prop"
  "erty name=\"xalign\">0</property></object><packing><property name=\"lef"
  "t_attach\">0</property><property name=\"top_attach\">1</property></pack"
  "ing></child><child><object class=\"GtkLabel\" id=\"label2\"><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">False</prop"
  "erty><property name=\"label\" translatable=\"yes\">_Layout:</property><"
  "property name=\"use_underline\">True</property><property name=\"xalign\""
  ">0</property></object><packing><property name=\"left_attach\">0</proper"
  "ty><property name=\"top_attach\">0</property></packing></child></object"
  "></child><child type=\"label\"><object class=\"GtkLabel\" id=\"label1\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"margin_bottom\">6</property><property"
  " name=\"label\" translatable=\"yes\">Appearance</property><attributes><"
  "attribute name=\"weight\" value=\"bold\"/></attributes></object></child"
  "></object><packing><property name=\"expand\">False</property><property "
  "name=\"fill\">True</property><property name=\"position\">1</property></"
  "packing></child><child><object class=\"GtkFrame\" id=\"frame1\"><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">False</"
  "property><property name=\"label_xalign\">0</property><property name=\"s"
  "hadow_type\">none</property><child><object class=\"GtkGrid\"><property "
  "name=\"visible\">True</property><property name=\"can_focus\">False</pro"
  "perty><property name=\"margin_left\">18</property><property name=\"hexp"
  "and\">True</property><property name=\"row_spacing\">6</property><proper"
  "ty name=\"column_spacing\">12</property><child><object class=\"GtkCheck"
  "Button\" id=\"show-meridiem\"><property name=\"label\" translatable=\"y"
  "es\">Sho_w AM/PM</property><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">True</property><property name=\"receives_def"
  "ault\">False</property><property name=\"use_underline\">True</property>"
  "<property name=\"draw_indicator\">True</property></object><packing><pro"
  "perty name=\"left_attach\">0</property><property name=\"top_attach\">4<"
  "/property><property name=\"width\">2</property></packing></child><child"
  "><object class=\"GtkCheckButton\" id=\"flash-separators\"><property nam"
  "e=\"label\" translatable=\"yes\">Fl_ash time separators</property><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">True<"
  "/property><property name=\"receives_default\">False</property><property"
  " name=\"use_underline\">True</property><property name=\"draw_indicator\""
  ">True</property></object><packing><property name=\"left_attach\">0</pro"
  "perty><property name=\"top_attach\">3</property><property name=\"width\""
  ">2</property></packing></child><child><object class=\"GtkCheckButton\" "
  "id=\"show-military\"><property name=\"label\" translatable=\"yes\">24-_"
  "hour clock</property><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">True</property><property name=\"receives_default\""
  ">False</property><property name=\"use_underline\">True</property><prope"
  "rty name=\"draw_indicator\">True</property></object><packing><property "
  "name=\"left_attach\">0</property><property name=\"top_attach\">2</prope"
  "rty><property name=\"width\">2</property></packing></child><child><obje"
  "ct class=\"GtkCheckButton\" id=\"true-binary\"><property name=\"label\""
  " translatable=\"yes\">True _binary clock</property><property name=\"vis"
  "ible\">True</property><property name=\"can_focus\">True</property><prop"
  "erty name=\"receives_default\">False</property><property name=\"use_und"
  "erline\">True</property><property name=\"draw_indicator\">True</propert"
  "y></object><packing><property name=\"left_attach\">0</property><propert"
  "y name=\"top_attach\">1</property><property name=\"width\">2</property>"
  "</packing></child><child><object class=\"GtkCheckButton\" id=\"show-sec"
  "onds\"><property name=\"label\" translatable=\"yes\">Display _seconds</"
  "property><property name=\"visible\">True</property><property name=\"can"
  "_focus\">True</property><property name=\"receives_default\">False</prop"
  "erty><property name=\"use_underline\">True</property><property name=\"d"
  "raw_indicator\">True</property></object><packing><property name=\"left_"
  "attach\">0</property><property name=\"top_attach\">0</property><propert"
  "y name=\"width\">2</property></packing></child><child><object class=\"G"
  "tkGrid\" id=\"digital-box\"><property name=\"visible\">True</property><"
  "property name=\"can_focus\">False</property><property name=\"hexpand\">"
  "True</property><property name=\"row_spacing\">6</property><property nam"
  "e=\"column_spacing\">12</property><child><object class=\"GtkComboBox\" "
  "id=\"digital-chooser\"><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">False</property><property name=\"hexpand\">True<"
  "/property><child><object class=\"GtkCellRendererText\" id=\"cellrendere"
  "rtext3\"/><attributes><attribute name=\"text\">2</attribute></attribute"
  "s></child></object><packing><property name=\"left_attach\">1</property>"
  "<property name=\"top_attach\">0</property></packing></child><child><obj"
  "ect class=\"GtkLabel\" id=\"label8\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">False</property><property name=\"l"
  "abel\" translatable=\"yes\">F_ormat:</property><property name=\"use_und"
  "erline\">True</property><property name=\"xalign\">0</property></object>"
  "<packing><property name=\"left_attach\">0</property><property name=\"to"
  "p_attach\">0</property></packing></child><child><object class=\"GtkEntr"
  "y\" id=\"digital-format\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">True</property><property name=\"hexpand\">Tru"
  "e</property><property name=\"secondary_icon_name\">help-contents</prope"
  "rty><property name=\"primary_icon_activatable\">False</property><proper"
  "ty name=\"secondary_icon_tooltip_text\" translatable=\"yes\">The format"
  " describes the date and time parts to insert into the panel. For exampl"
  "e, %Y will be substituted with the year, %m with the month and %d with "
  "the day. Similarly, &lt;b&gt;&lt;/b&gt; tags will make the text bold. S"
  "ee the \"Help\" page for additional information.</property></object><pa"
  "cking><property name=\"left_attach\">0</property><property name=\"top_a"
  "ttach\">1</property><property name=\"width\">2</property></packing></ch"
  "ild></object><packing><property name=\"left_attach\">0</property><prope"
  "rty name=\"top_attach\">5</property><property name=\"width\">2</propert"
  "y></packing></child><child><object class=\"GtkBox\" id=\"fuzziness-box\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><child><object class=\"GtkLabel\" id=\"label5\"><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">False<"
  "/property><property name=\"label\" translatable=\"yes\" comments=\"I18N"
  ": the fuzziness the *precision* of the fuzzy clock. Time steps of 5, 15"
  " or parts of the day.\">F_uzziness:</property><property name=\"use_unde"
  "rline\">True</property><property name=\"xalign\">0</property></object><"
  "packing><property name=\"expand\">False</property><property name=\"fill"
  "\">True</property><property name=\"position\">0</property></packing></c"
  "hild><child><object class=\"GtkScale\" id=\"hscale1\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">True</property><p"
  "roperty name=\"hexpand\">True</property><property name=\"adjustment\">f"
  "uzziness</property><property name=\"digits\">0</property><property name"
  "=\"value_pos\">right</property></object><packing><property name=\"expan"
  "d\">True</property><property name=\"fill\">True</property><property nam"
  "e=\"position\">1</property></packing></child></object><packing><propert"
  "y name=\"left_attach\">0</property><property name=\"top_attach\">6</pro"
  "perty><property name=\"width\">2</property></packing></child><child><ob"
  "ject class=\"GtkCheckButton\" id=\"show-inactive\"><property name=\"lab"
  "el\" translatable=\"yes\">Show _inactive dots</property><property name="
  "\"visible\">True</property><property name=\"can_focus\">True</property>"
  "<property name=\"receives_default\">False</property><property name=\"us"
  "e_underline\">True</property><property name=\"draw_indicator\">True</pr"
  "operty></object><packing><property name=\"left_attach\">0</property><pr"
  "operty name=\"top_attach\">7</property><property name=\"width\">2</prop"
  "erty></packing></child><child><object class=\"GtkCheckButton\" id=\"sho"
  "w-grid\"><property name=\"label\" translatable=\"yes\">Show gri_d</prop"
  "erty><property name=\"visible\">True</property><property name=\"can_foc"
  "us\">True</property><property name=\"receives_default\">False</property"
  "><property name=\"use_underline\">True</property><property name=\"draw_"
  "indicator\">True</property></object><packing><property name=\"left_atta"
  "ch\">0</property><property name=\"top_attach\">8</property><property na"
  "me=\"width\">2</property></packing></child></object></child><child type"
  "=\"label\"><object class=\"GtkLabel\" id=\"label3\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">False</property><pr"
  "operty name=\"margin_bottom\">6</property><property name=\"label\" tran"
  "slatable=\"yes\">Clock Options</property><attributes><attribute name=\""
  "weight\" value=\"bold\"/></attributes></object></child></object><packin"
  "g><property name=\"expand\">False</property><property name=\"fill\">Tru"
  "e</property><property name=\"position\">2</property></packing></child><"
  "/object><packing><property name=\"expand\">True</property><property nam"
  "e=\"fill\">True</property><property name=\"position\">1</property></pac"
  "king></child></object></child><action-widgets><action-widget response=\""
  "0\">close-button</action-widget><action-widget response=\"0\">help-butt"
  "on</action-widget></action-widgets></object></interface>"
};

static const unsigned clock_dialog_ui_length = 17598u;

