/* automatically generated from tasklist-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (tasklist_dialog_ui)
#endif
#ifdef __GNUC__
static const char tasklist_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char tasklist_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.20\"/><requires lib=\"libxfce4ui-2\" version=\"4.12\"/"
  "><object class=\"GtkListStore\" id=\"grouping-model\"><columns><column "
  "type=\"gchararray\"/></columns><data><row><col id=\"0\" translatable=\""
  "yes\">Never</col></row><row><col id=\"0\" translatable=\"yes\">Always</"
  "col></row><row><col id=\"0\" translatable=\"yes\">When space is limited"
  "</col></row></data></object><object class=\"GtkImage\" id=\"image1\"><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Fa"
  "lse</property><property name=\"icon_name\">help-browser</property></obj"
  "ect><object class=\"GtkImage\" id=\"image2\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"icon_name\">window-close-symbolic</property></object><object cla"
  "ss=\"GtkListStore\" id=\"middle-click-model\"><columns><column type=\"g"
  "chararray\"/></columns><data><row><col id=\"0\" translatable=\"yes\">No"
  "thing</col></row><row><col id=\"0\" translatable=\"yes\">Close Window</"
  "col></row><row><col id=\"0\" translatable=\"yes\">Minimize Window</col>"
  "</row></data></object><object class=\"GtkListStore\" id=\"sort-order-mo"
  "del\"><columns><column type=\"gchararray\"/></columns><data><row><col i"
  "d=\"0\" translatable=\"yes\">Timestamp</col></row><row><col id=\"0\" tr"
  "anslatable=\"yes\">Group title and timestamp</col></row><row><col id=\""
  "0\" translatable=\"yes\">Window title</col></row><row><col id=\"0\" tra"
  "nslatable=\"yes\">Group title and window title</col></row><row><col id="
  "\"0\" translatable=\"yes\">None, allow drag-and-drop</col></row></data>"
  "</object><object class=\"XfceTitledDialog\" id=\"dialog\"><property nam"
  "e=\"can_focus\">False</property><property name=\"title\" translatable=\""
  "yes\">Window Buttons</property><property name=\"icon_name\">org.xfce.pa"
  "nel.tasklist</property><property name=\"type_hint\">normal</property><c"
  "hild internal-child=\"vbox\"><object class=\"GtkBox\" id=\"dialog-vbox2"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">False</property><property name=\"orientation\">vertical</property><p"
  "roperty name=\"spacing\">2</property><child internal-child=\"action_are"
  "a\"><object class=\"GtkButtonBox\" id=\"dialog-action_area2\"><property"
  " name=\"visible\">True</property><property name=\"can_focus\">False</pr"
  "operty><property name=\"layout_style\">end</property><child><object cla"
  "ss=\"GtkButton\" id=\"close-button\"><property name=\"label\" translata"
  "ble=\"yes\">_Close</property><property name=\"use_action_appearance\">F"
  "alse</property><property name=\"visible\">True</property><property name"
  "=\"can_focus\">True</property><property name=\"receives_default\">True<"
  "/property><property name=\"image\">image2</property><property name=\"us"
  "e_underline\">True</property></object><packing><property name=\"expand\""
  ">False</property><property name=\"fill\">False</property><property name"
  "=\"position\">0</property></packing></child><child><object class=\"GtkB"
  "utton\" id=\"help-button\"><property name=\"label\" translatable=\"yes\""
  ">_Help</property><property name=\"use_action_appearance\">False</proper"
  "ty><property name=\"visible\">True</property><property name=\"can_focus"
  "\">True</property><property name=\"receives_default\">True</property><p"
  "roperty name=\"image\">image1</property><property name=\"use_underline\""
  ">True</property></object><packing><property name=\"expand\">False</prop"
  "erty><property name=\"fill\">False</property><property name=\"position\""
  ">1</property><property name=\"secondary\">True</property></packing></ch"
  "ild></object><packing><property name=\"expand\">False</property><proper"
  "ty name=\"fill\">True</property><property name=\"pack_type\">end</prope"
  "rty><property name=\"position\">0</property></packing></child><child><o"
  "bject class=\"GtkBox\" id=\"vbox1\"><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">False</property><property name=\"bo"
  "rder_width\">6</property><property name=\"orientation\">vertical</prope"
  "rty><property name=\"spacing\">6</property><child><object class=\"GtkFr"
  "ame\" id=\"frame3\"><property name=\"visible\">True</property><property"
  " name=\"can_focus\">False</property><property name=\"label_xalign\">0</"
  "property><property name=\"shadow_type\">none</property><child><object c"
  "lass=\"GtkAlignment\" id=\"alignment3\"><property name=\"visible\">True"
  "</property><property name=\"can_focus\">False</property><property name="
  "\"left_padding\">12</property><child><object class=\"GtkBox\" id=\"vbox"
  "3\"><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">False</property><property name=\"border_width\">6</property><proper"
  "ty name=\"orientation\">vertical</property><property name=\"spacing\">6"
  "</property><child><object class=\"GtkCheckButton\" id=\"show-labels\"><"
  "property name=\"label\" translatable=\"yes\">Show button _labels</prope"
  "rty><property name=\"use_action_appearance\">False</property><property "
  "name=\"visible\">True</property><property name=\"can_focus\">True</prop"
  "erty><property name=\"receives_default\">False</property><property name"
  "=\"use_underline\">True</property><property name=\"draw_indicator\">Tru"
  "e</property></object><packing><property name=\"expand\">True</property>"
  "<property name=\"fill\">True</property><property name=\"position\">0</p"
  "roperty></packing></child><child><object class=\"GtkCheckButton\" id=\""
  "flat-buttons\"><property name=\"label\" translatable=\"yes\">Show _flat"
  " buttons</property><property name=\"use_action_appearance\">False</prop"
  "erty><property name=\"visible\">True</property><property name=\"can_foc"
  "us\">True</property><property name=\"receives_default\">False</property"
  "><property name=\"use_underline\">True</property><property name=\"draw_"
  "indicator\">True</property></object><packing><property name=\"expand\">"
  "True</property><property name=\"fill\">True</property><property name=\""
  "position\">1</property></packing></child><child><object class=\"GtkChec"
  "kButton\" id=\"show-handle\"><property name=\"label\" translatable=\"ye"
  "s\">Show _handle</property><property name=\"use_action_appearance\">Fal"
  "se</property><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"receives_default\">False</p"
  "roperty><property name=\"use_underline\">True</property><property name="
  "\"draw_indicator\">True</property></object><packing><property name=\"ex"
  "pand\">True</property><property name=\"fill\">True</property><property "
  "name=\"position\">2</property></packing></child><child><object class=\""
  "GtkBox\" id=\"hbox2\"><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">False</property><property name=\"spacing\">12</pr"
  "operty><child><object class=\"GtkLabel\" id=\"label5\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"label\" translatable=\"yes\">Sorting _order:</property>"
  "<property name=\"use_underline\">True</property><property name=\"mnemon"
  "ic_widget\">sort-order</property></object><packing><property name=\"exp"
  "and\">False</property><property name=\"fill\">True</property><property "
  "name=\"position\">0</property></packing></child><child><object class=\""
  "GtkComboBox\" id=\"sort-order\"><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">False</property><property name=\"model\""
  ">sort-order-model</property><child><object class=\"GtkCellRendererText\""
  " id=\"cellrenderertext1\"/><attributes><attribute name=\"text\">0</attr"
  "ibute></attributes></child></object><packing><property name=\"expand\">"
  "False</property><property name=\"fill\">True</property><property name=\""
  "position\">1</property></packing></child></object><packing><property na"
  "me=\"expand\">True</property><property name=\"fill\">True</property><pr"
  "operty name=\"position\">3</property></packing></child></object></child"
  "></object></child><child type=\"label\"><object class=\"GtkLabel\" id=\""
  "label1\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"label\" translatable=\"yes\">"
  "Appearance</property><attributes><attribute name=\"weight\" value=\"bol"
  "d\"/></attributes></object></child></object><packing><property name=\"e"
  "xpand\">False</property><property name=\"fill\">True</property><propert"
  "y name=\"position\">0</property></packing></child><child><object class="
  "\"GtkFrame\" id=\"frame1\"><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">False</property><property name=\"label_xalig"
  "n\">0</property><property name=\"shadow_type\">none</property><child><o"
  "bject class=\"GtkAlignment\" id=\"alignment1\"><property name=\"visible"
  "\">True</property><property name=\"can_focus\">False</property><propert"
  "y name=\"left_padding\">12</property><child><object class=\"GtkBox\" id"
  "=\"vbox2\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">False</property><property name=\"border_width\">6</property>"
  "<property name=\"orientation\">vertical</property><property name=\"spac"
  "ing\">6</property><child><object class=\"GtkBox\" id=\"hbox1\"><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">False</p"
  "roperty><property name=\"spacing\">12</property><child><object class=\""
  "GtkLabel\" id=\"label4\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"label\" trans"
  "latable=\"yes\">Window _grouping:</property><property name=\"use_underl"
  "ine\">True</property><property name=\"mnemonic_widget\">grouping</prope"
  "rty><property name=\"xalign\">0</property></object><packing><property n"
  "ame=\"expand\">False</property><property name=\"fill\">True</property><"
  "property name=\"position\">0</property></packing></child><child><object"
  " class=\"GtkComboBox\" id=\"grouping\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property name=\""
  "model\">grouping-model</property><child><object class=\"GtkCellRenderer"
  "Text\" id=\"cellrenderertext2\"/><attributes><attribute name=\"text\">0"
  "</attribute></attributes></child></object><packing><property name=\"exp"
  "and\">False</property><property name=\"fill\">True</property><property "
  "name=\"position\">1</property></packing></child></object><packing><prop"
  "erty name=\"expand\">True</property><property name=\"fill\">True</prope"
  "rty><property name=\"position\">0</property></packing></child><child><o"
  "bject class=\"GtkBox\" id=\"hbox3\"><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">False</property><property name=\"sp"
  "acing\">12</property><child><object class=\"GtkLabel\" id=\"label6\"><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Fa"
  "lse</property><property name=\"label\" translatable=\"yes\">Mi_ddle cli"
  "ck action:</property><property name=\"use_underline\">True</property><p"
  "roperty name=\"mnemonic_widget\">middle-click</property><property name="
  "\"xalign\">0</property></object><packing><property name=\"expand\">Fals"
  "e</property><property name=\"fill\">True</property><property name=\"pos"
  "ition\">0</property></packing></child><child><object class=\"GtkComboBo"
  "x\" id=\"middle-click\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">False</property><property name=\"model\">middle"
  "-click-model</property><child><object class=\"GtkCellRendererText\" id="
  "\"cellrenderertext3\"/><attributes><attribute name=\"text\">0</attribut"
  "e></attributes></child></object><packing><property name=\"expand\">Fals"
  "e</property><property name=\"fill\">True</property><property name=\"pos"
  "ition\">1</property></packing></child></object><packing><property name="
  "\"expand\">True</property><property name=\"fill\">True</property><prope"
  "rty name=\"position\">1</property></packing></child><child><object clas"
  "s=\"GtkCheckButton\" id=\"switch-workspace-on-unminimize\"><property na"
  "me=\"label\" translatable=\"yes\">Restore minimized windows to current "
  "_workspace</property><property name=\"use_action_appearance\">False</pr"
  "operty><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">True</property><property name=\"receives_default\">False</proper"
  "ty><property name=\"use_underline\">True</property><property name=\"dra"
  "w_indicator\">True</property></object><packing><property name=\"expand\""
  ">True</property><property name=\"fill\">True</property><property name=\""
  "position\">2</property></packing></child><child><object class=\"GtkChec"
  "kButton\" id=\"show-wireframes\"><property name=\"label\" translatable="
  "\"yes\">D_raw window frame when hovering a button</property><property n"
  "ame=\"use_action_appearance\">False</property><property name=\"visible\""
  ">True</property><property name=\"can_focus\">True</property><property n"
  "ame=\"receives_default\">False</property><property name=\"use_underline"
  "\">True</property><property name=\"draw_indicator\">True</property></ob"
  "ject><packing><property name=\"expand\">True</property><property name=\""
  "fill\">True</property><property name=\"position\">3</property></packing"
  "></child><child><object class=\"GtkCheckButton\" id=\"window-scrolling\""
  "><property name=\"label\" translatable=\"yes\">_Switch windows using th"
  "e mouse wheel</property><property name=\"use_action_appearance\">False<"
  "/property><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">True</property><property name=\"receives_default\">False</pro"
  "perty><property name=\"use_underline\">True</property><property name=\""
  "draw_indicator\">True</property></object><packing><property name=\"expa"
  "nd\">True</property><property name=\"fill\">True</property><property na"
  "me=\"position\">4</property></packing></child></object></child></object"
  "></child><child type=\"label\"><object class=\"GtkLabel\" id=\"label3\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"label\" translatable=\"yes\">Behaviou"
  "r</property><attributes><attribute name=\"weight\" value=\"bold\"/></at"
  "tributes></object></child></object><packing><property name=\"expand\">F"
  "alse</property><property name=\"fill\">True</property><property name=\""
  "position\">1</property></packing></child><child><object class=\"GtkFram"
  "e\" id=\"frame2\"><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">False</property><property name=\"label_xalign\">0</pr"
  "operty><property name=\"shadow_type\">none</property><child><object cla"
  "ss=\"GtkAlignment\" id=\"alignment2\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">False</property><property name=\""
  "left_padding\">12</property><child><object class=\"GtkBox\" id=\"vbox4\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"border_width\">6</property><property "
  "name=\"orientation\">vertical</property><property name=\"spacing\">6</p"
  "roperty><child><object class=\"GtkCheckButton\" id=\"include-all-worksp"
  "aces\"><property name=\"label\" translatable=\"yes\">Show windows from "
  "_all workspaces or viewports</property><property name=\"use_action_appe"
  "arance\">False</property><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">True</property><property name=\"receives_defau"
  "lt\">False</property><property name=\"use_underline\">True</property><p"
  "roperty name=\"draw_indicator\">True</property></object><packing><prope"
  "rty name=\"expand\">True</property><property name=\"fill\">True</proper"
  "ty><property name=\"position\">0</property></packing></child><child><ob"
  "ject class=\"GtkCheckButton\" id=\"include-all-monitors\"><property nam"
  "e=\"label\" translatable=\"yes\">Show windows from all mo_nitors</prope"
  "rty><property name=\"use_action_appearance\">False</property><property "
  "name=\"visible\">True</property><property name=\"can_focus\">True</prop"
  "erty><property name=\"receives_default\">False</property><property name"
  "=\"use_underline\">True</property><property name=\"draw_indicator\">Tru"
  "e</property></object><packing><property name=\"expand\">True</property>"
  "<property name=\"fill\">True</property><property name=\"position\">1</p"
  "roperty></packing></child><child><object class=\"GtkCheckButton\" id=\""
  "show-only-minimized\"><property name=\"label\" translatable=\"yes\">Sho"
  "w only _minimized windows</property><property name=\"use_action_appeara"
  "nce\">False</property><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">True</property><property name=\"receives_default\""
  ">False</property><property name=\"use_underline\">True</property><prope"
  "rty name=\"draw_indicator\">True</property></object><packing><property "
  "name=\"expand\">True</property><property name=\"fill\">True</property><"
  "property name=\"position\">1</property></packing></child></object></chi"
  "ld></object></child><child type=\"label\"><object class=\"GtkLabel\" id"
  "=\"label2\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"label\" translatable=\"yes"
  "\">Filtering</property><attributes><attribute name=\"weight\" value=\"b"
  "old\"/></attributes></object></child></object><packing><property name=\""
  "expand\">True</property><property name=\"fill\">True</property><propert"
  "y name=\"position\">2</property></packing></child></object><packing><pr"
  "operty name=\"expand\">False</property><property name=\"fill\">True</pr"
  "operty><property name=\"position\">1</property></packing></child></obje"
  "ct></child><action-widgets><action-widget response=\"0\">close-button</"
  "action-widget><action-widget response=\"0\">help-button</action-widget>"
  "</action-widgets></object><object class=\"GtkSizeGroup\" id=\"sizegroup"
  "1\"><widgets><widget name=\"label4\"/><widget name=\"label6\"/></widget"
  "s></object></interface>"
};

static const unsigned tasklist_dialog_ui_length = 16541u;

